export const getData = () => {
    return {
        mon: {
        '08': {
          event: {
            id: '1',
            pnumber: '3',
            tools: 'sim',
            day: '28/11/2022',
            time: '08:00:00',
            user: {
              id: '1',
              name: 'Bruno',
              ra: '202120043',
            },
          },
        },
        '09': {},
        '10': {},
        '11': {},
        '12': {},
        '13': {
          event: {
            id: '2',
            pnumber: '4',
            tools: 'não',
            day: '28/11/2022',
            time: '13:00:00',
            user: {
              id: '2',
              name: 'Pedro',
              ra: '202110520',
            },
          },
        },
        '14': {},
        '15': {},
        '16': {
          event: {
            id: '3',
            pnumber: '2',
            tools: 'sim',
            day: '28/11/2022',
            time: '16:00:00',
            user: {
              id: '3',
              name: 'Teddy',
              ra: '202110052',
            },
          },
        },
        '17': {},
        '18': {},
        '19': {},
      },
      tue: {
        '08': {
          event: {
            id: '1',
            pnumber: '25',
            tools: 'sim',
            day: '29/11/2022',
            time: '08:00:00',
            user: {
              id: '1',
              name: 'Aula',
              ra: '0',
            },
          },
        },
        '09': {
          event: {
            id: '1',
            pnumber: '25',
            tools: 'sim',
            day: '29/11/2022',
            time: '09:00:00',
            user: {
              id: '1',
              name: 'Aula',
              ra: '0',
            },
          },
        },
        '10': {},
        '11': {},
        '12': {},
        '13': {},
        '14': {
          event: {
            id: '1',
            pnumber: '30',
            tools: 'sim',
            day: '29/11/2022',
            time: '14:00:00',
            user: {
              id: '1',
              name: 'Aula 2',
              ra: '0',
            },
          },
        },
        '15': {
          event: {
            id: '1',
            pnumber: '30',
            tools: 'sim',
            day: '29/11/2022',
            time: '15:00:00',
            user: {
              id: '1',
              name: 'Aula 2',
              ra: '0',
            },
          },
        },
        '16': {},
        '17': {},
        '18': {},
        '19': {},
      },
      wed: {
        '08': {},
        '09': {},
        '10': {event: {
          id: '1',
          pnumber: '3',
          tools: 'sim',
          day: '30/11/2022',
          time: '10:00:00',
          user: {
            id: '1',
            name: 'Tiago',
            ra: '202120043',
          },
        },
        },
        '11': {},
        '12': {},
        '13': {
          event: {
            id: '2',
            pnumber: '4',
            tools: 'não',
            day: '30/11/2022',
            time: '13:00:00',
            user: {
              id: '2',
              name: 'Matheus',
              ra: '202110520',
            },
          },
        },
        '14': {},
        '15': {},
        '16': {},
        '17': {},
        '18': {},
        '19': {
          event: {
            id: '3',
            pnumber: '2',
            tools: 'sim',
            day: '30/11/2022',
            time: '19:00:00',
            user: {
              id: '3',
              name: 'Rafael',
              ra: '202110052',
            },
          },
        },
      },
      thu: {
        '08': {},
        '09': {},
        '10': {
          event: {
            id: '1',
            pnumber: '15',
            tools: 'sim',
            day: '01/12/2022',
            time: '10:00:00',
            user: {
              id: '1',
              name: 'Aula 3',
              ra: '0',
            },
          },
        },
        '11': {
          event: {
            id: '1',
            pnumber: '15',
            tools: 'sim',
            day: '01/12/2022',
            time: '11:00:00',
            user: {
              id: '1',
              name: 'Aula 3',
              ra: '0',
            },
          },
        },
        '12': {},
        '13': {},
        '14': {},
        '15': {},
        '16': {},
        '17': {},
        '18': {},
        '19': {},
      },
      fri: {
        '08': {},
        '09': {event: {
          id: '1',
          pnumber: '2',
          tools: 'sim',
          day: '02/12/2022',
          time: '09:00:00',
          user: {
            id: '1',
            name: 'Gustavo',
            ra: '202110256',
          },
        },
      },
        '10': {},
        '11': {},
        '12': {},
        '13': {},
        '14': {},
        '15': {
          event: {
            id: '2',
            pnumber: '7',
            tools: 'sim',
            day: '02/12/2022',
            time: '15:00:00',
            user: {
              id: '2',
              name: 'Alexandre',
              ra: '202110532',
            },
          },
        },
        '16': {},
        '17': {},
        '18': {
          event: {
            id: '3',
            pnumber: '2',
            tools: 'sim',
            day: '02/12/2022',
            time: '18:00:00',
            user: {
              id: '3',
              name: 'Luca',
              ra: '202110234',
            },
          },
        },
        '19': {},
    },}
};